// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/google/wire"
	"github.com/logica0419/remote-bmi/server/repository"
	"github.com/logica0419/remote-bmi/server/router"
)

// Injectors from wire.go:

func setupRouter(cfg *Config) (*router.Router, error) {
	config := newRouterConfig(cfg)
	repositoryConfig := newRepositoryConfig(cfg)
	repositoryRepository, err := repository.NewRepository(repositoryConfig)
	if err != nil {
		return nil, err
	}
	routerRouter := router.NewRouter(config, repositoryRepository)
	return routerRouter, nil
}

// wire.go:

var set = wire.NewSet(
	newRepositoryConfig, repository.NewRepository, newRouterConfig, router.NewRouter,
)
